WINDOW_SIZE = 30
TARGET_FPS = 10
SAMPLE_INTERVAL_SEC = 1.0 / TARGET_FPS

FEATURE_DIM = 166
EXPECTED_SAMPLE_SHAPE = (WINDOW_SIZE, FEATURE_DIM)

DATA_DIR_NAME = "data_processed_arm_pose_10fps"
MODEL_FILE_NAME = "gesture_cnn_arm_pose_10fps.keras"
LABEL_MAP_FILE_NAME = "label_map_arm_pose_10fps.json"

SWAP_HANDEDNESS = True
SWAP_POSE_LR = True
POSE_VISIBILITY_THRESHOLD = 0.5

RAW_PHONE_DATA_DIR_NAME = "dataset_raw_phone_10fps"
RAW_SAMPLE_FRAME_COUNT = WINDOW_SIZE
RAW_REQUIRE_SHOULDERS = True
RAW_REQUIRE_HAND = True